version: "3.9"
services:
  web:
    build: "../ida-service"
    environment:
      - AWS_ACCESS_KEY_ID={YOUR_AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY={YOUR_AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=eu-west-1
    ports:
      - "5000:5000"
    depends_on:
      camunda:
          condition: service_healthy
    links:
        - camunda
            
  camunda:
    build: "./process-application"
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:8080/engine-rest/engine"]
      interval: 30s
      timeout: 10s
      retries: 5
